import { App, Button, Card, Col, Form, Input, List, Modal, Radio, Row, Select, Space, Typography } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import NotificationMarkdown from '../../components/notifications/NotificationMarkdown'
import { resolveApiErrorMessage } from '../../lib/error'
import { listNotificationRecipients, listPublishedNotifications, publishNotification, updatePublishedNotification } from '../../lib/notifications'
import type { AdminNotification, NotificationRecipient } from '../../lib/types'

type PublishValues = { audience: 'users' | 'active_users'; recipient_user_ids?: number[]; title: string; body_markdown: string }
type EditValues = Pick<AdminNotification, 'title' | 'body_markdown'>

function MarkdownPreview({ title, content }: { title?: string; content?: string }) { return <Card size="small" title="实时预览"><Typography.Title level={4}>{title || '消息标题'}</Typography.Title><NotificationMarkdown content={content || '在左侧输入 Markdown 后会在这里预览。'} /></Card> }

export default function NotificationManagementPage() {
  const { message } = App.useApp(); const [recipients, setRecipients] = useState<NotificationRecipient[]>([]); const [records, setRecords] = useState<AdminNotification[]>([]); const [editing, setEditing] = useState<AdminNotification | null>(null); const [publishing, setPublishing] = useState(false); const [saving, setSaving] = useState(false)
  const [form] = Form.useForm<PublishValues>(); const [editForm] = Form.useForm<EditValues>(); const audience = Form.useWatch('audience', form) ?? 'active_users'; const draftTitle = Form.useWatch('title', form); const draftBody = Form.useWatch('body_markdown', form); const editTitle = Form.useWatch('title', editForm); const editBody = Form.useWatch('body_markdown', editForm)
  const loadRecords = useCallback(() => { void listPublishedNotifications().then((value) => setRecords(value.items)).catch((error) => message.error(resolveApiErrorMessage(error))) }, [message])
  useEffect(() => { void listNotificationRecipients().then(setRecipients).catch((error) => message.error(resolveApiErrorMessage(error))); loadRecords() }, [loadRecords, message])
  const submit = async (values: PublishValues) => { setPublishing(true); try { const result = await publishNotification(values); message.success(`通知已发布给 ${result.recipient_count} 位用户`); form.resetFields(); form.setFieldValue('audience', 'active_users'); loadRecords() } catch (error) { message.error(resolveApiErrorMessage(error, '发布失败，请稍后重试。')) } finally { setPublishing(false) } }
  const saveEdit = async (values: EditValues) => { if (!editing) return; setSaving(true); try { await updatePublishedNotification(editing.id, values); message.success('消息已更新'); setEditing(null); loadRecords() } catch (error) { message.error(resolveApiErrorMessage(error, '保存修改失败，请稍后重试。')) } finally { setSaving(false) } }
  const openEdit = (item: AdminNotification) => { setEditing(item); editForm.setFieldsValue(item) }; const options = recipients.map((u) => ({ value: u.id, label: `${u.username}${u.name ? ` (${u.name})` : ''}` }))
  return <Space direction="vertical" size={16} style={{ width: '100%' }}><Card><Typography.Title level={4}>发布站内消息</Typography.Title><Typography.Paragraph type="secondary">发布后立即送达，右侧展示最终安全渲染结果。</Typography.Paragraph><Row gutter={[24, 16]}><Col xs={24} lg={12}><Form form={form} layout="vertical" initialValues={{ audience: 'active_users' }} onFinish={submit}><Form.Item name="audience" label="接收范围"><Radio.Group disabled={publishing}><Radio value="active_users">全体活跃用户</Radio><Radio value="users">指定用户</Radio></Radio.Group></Form.Item>{audience === 'users' && <Form.Item name="recipient_user_ids" label="接收用户" rules={[{ required: true }]}><Select mode="multiple" showSearch disabled={publishing} optionFilterProp="label" options={options} /></Form.Item>}<Form.Item name="title" label="标题" rules={[{ required: true, max: 200 }]}><Input disabled={publishing} /></Form.Item><Form.Item name="body_markdown" label="Markdown 正文" rules={[{ required: true, max: 20000 }]}><Input.TextArea rows={10} disabled={publishing} /></Form.Item><Button type="primary" htmlType="submit" loading={publishing}>立即发布</Button></Form></Col><Col xs={24} lg={12}><MarkdownPreview title={draftTitle} content={draftBody} /></Col></Row></Card><Card title="发布记录"><List dataSource={records} locale={{ emptyText: '暂无发布记录' }} renderItem={(item) => <List.Item actions={[<Button key="edit" onClick={() => openEdit(item)}>编辑</Button>]}><List.Item.Meta title={item.title} description={`${new Date(item.created_at).toLocaleString()} · ${item.recipient_count} 位接收人`} /></List.Item>} /></Card><Modal title="编辑站内消息" open={Boolean(editing)} onCancel={() => !saving && setEditing(null)} closable={!saving} footer={null} width={1000}><Row gutter={[24, 16]}><Col xs={24} lg={12}><Form form={editForm} layout="vertical" onFinish={saveEdit}><Form.Item name="title" label="标题" rules={[{ required: true, max: 200 }]}><Input disabled={saving} /></Form.Item><Form.Item name="body_markdown" label="Markdown 正文" rules={[{ required: true, max: 20000 }]}><Input.TextArea rows={12} disabled={saving} /></Form.Item><Button type="primary" htmlType="submit" loading={saving}>保存修改</Button></Form></Col><Col xs={24} lg={12}><MarkdownPreview title={editTitle} content={editBody} /></Col></Row></Modal></Space>
}
